#version: '3.8'

# Nginx는 API 컨테이너들과 같은 네트워크를 씁니다.
services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy #container_name 지정안하면 [프로젝트 폴더명]-[서비스명]-[번호] zero-downtime-test-nginx-proxy-1
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  api-blue:
    image: zero-api:${IMAGE_TAG:-latest}
    build: .
    ports:
      - "8080:8080" # 외부 헬스체크용 포트 개방

  api-green:
    image: zero-api:${IMAGE_TAG:-latest}
    build: .
    ports:
      - "8081:8080" # 외부 헬스체크용 포트 개방