events {
    worker_connections 1024;
}

http {
    #브라우저의 Keep-Alive(연결 유지) 고집을 꺾는 설정 추가
    keepalive_timeout 0;

    upstream backend {
        # 초기에는 api-blue 컨테이너의 8080 포트를 바라봅니다.
        # (Docker Compose 네트워크 덕분에 컨테이너 이름으로 통신 가능)
        server api-blue:8080; 
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_read_timeout 300s;
            proxy_connect_timeout 300s;
            proxy_send_timeout 300s;
        }
    }
}