name: Zero-Downtime Deployment (Self-Hosted)

# 언제 실행할 것인가?
on:
  push:
    branches: [ "develop" ] # main 브랜치에 코드가 들어올 때 자동 실행
  workflow_dispatch:     # GitHub 웹페이지에서 수동으로 버튼을 누를 때도 실행 가능 (살려두는 것을 강력 추천합니다!)

jobs:
  deploy:
    runs-on: [self-hosted, dev]

    steps:
      # 1. GitHub 창고에 있는 최신 코드를 가상머신(로봇의 현재 폴더)으로 다운로드
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. 다운로드한 폴더 안의 deploy.sh 스크립트 실행 및 DB 주소 주입
      - name: Execute Deployment Script
        env:
          # GitHub Secrets에 숨겨둔 진짜 DB 주소를 꺼내서 'DB_URL' 이라는 이름표를 붙여줍니다.
          DB_URL: ${{ secrets.PROD_DB_CONNECTION }}
        run: |
          # 2-1. 도커 컴포즈가 이 값을 읽을 수 있도록 리눅스 메모리에 확실하게 각인(export) 시킵니다.
          export DB_URL=$DB_URL
          
          # 2-2. 스크립트에 실행 권한 부여
          chmod +x deploy.sh
          
          # 2-3. 쉘 스크립트 실행 (이 안에서 도커 빌드, 무중단 스위칭, DB 주소 전달이 모두 일어납니다)
          bash deploy.sh


# Environments Required reviewers => 승인 후 배포에 대해서 알아보기